<script lang="ts">
    import {requestHistory,clearRequestHistory} from '@/lib/requestHistory'
    import {invoke} from '@tauri-apps/api/core'
    import {requestStats} from '@/lib/requestStats'
    let query='',source='all',visible=50
    let terminalError='',terminalBusy=false
    async function terminal(show:boolean){terminalBusy=true;terminalError='';try{await invoke('set_jarvis_terminal_visible',{visible:show})}catch(e){terminalError=String(e)}finally{terminalBusy=false}}
    $: filtered=$requestHistory.filter(item=>(source==='all'||item.source===source)&&item.text.toLocaleLowerCase('ru-RU').includes(query.toLocaleLowerCase('ru-RU')))
    $: {query;source;visible=50}
    $: chatCount=filtered.filter(item=>item.source==='chat').length
    $: voiceCount=filtered.length-chatCount
    $: chatShare=filtered.length?chatCount/filtered.length*100:0
    $: days=Array.from({length:14},(_,index)=>{const date=new Date();date.setHours(0,0,0,0);date.setDate(date.getDate()-13+index);const end=new Date(date);end.setDate(end.getDate()+1);return {label:date.toLocaleDateString('ru-RU',{day:'numeric',month:'short'}),count:filtered.filter(item=>Date.parse(item.at)>=date.getTime()&&Date.parse(item.at)<end.getTime()).length}})
    $: maxDay=Math.max(1,...days.map(day=>day.count))
    $: stats=requestStats(filtered)
</script>
<section class="history" aria-label="История запросов">
    <header><div><p>JARVIS / REQUEST LOG</p><h2>История запросов</h2><small>Последние 500 запросов · хранится на этом компьютере</small></div><button disabled={!$requestHistory.length} on:click={()=>{if(confirm('Удалить всю историю запросов?'))clearRequestHistory()}}>Очистить историю</button></header>
    <div class="categories" aria-label="Категории истории">{#each [{id:'all',name:'Все запросы'},{id:'chat',name:'История чата'},{id:'voice',name:'Голосовые команды'}] as category}<button aria-pressed={source===category.id} on:click={()=>source=category.id}>{category.name}</button>{/each}</div>
    <div class="terminal"><span>Терминал JARVIS</span><button disabled={terminalBusy} on:click={()=>terminal(false)}>Скрыть терминал</button><button disabled={terminalBusy} on:click={()=>terminal(true)}>Открыть терминал</button></div>
    {#if terminalError}<p role="alert">{terminalError}</p>{/if}
    <div class="filters"><input aria-label="Поиск по истории запросов" placeholder="Найти запрос…" bind:value={query}/></div>
    <div class="charts"><section><h3>Запросы по источникам</h3><small>Выбранная категория и поиск · {filtered.length} записей</small><div class="mix"><div class="donut" role="img" aria-label={`Чат: ${chatCount}, голос: ${voiceCount}`} style:background={filtered.length?`conic-gradient(#60f3e9 ${chatShare}%, #9ba9ff 0)`:'#28494f'}><strong>{filtered.length}</strong></div><div><p>● Чат <b>{chatCount}</b></p><p>◇ Голос <b>{voiceCount}</b></p></div></div></section><section><h3>Активность за 14 дней</h3><small>Количество записанных запросов в день · от нуля</small><div class="bars" role="img" aria-label={days.map(day=>`${day.label}: ${day.count}`).join('; ')}>{#each days as day}<div title={`${day.label}: ${day.count}`}><b>{day.count}</b><span style:height={`${day.count/maxDay*100}px`}></span><small>{day.label}</small></div>{/each}</div></section></div>
    <div class="charts extra-charts">
        <section><div class="chart-heading"><span class="chart-icon">◷</span><div><h3>Активность по часам</h3><small>{filtered.length} запросов · часы по времени компьютера</small></div></div>
            {#if filtered.length}<div class="hour-grid" role="img" aria-label={stats.hours.map((count,hour)=>`${hour}:00 — ${count}`).join('; ')}>{#each stats.hours as count,hour}<div class="hour-cell" title={`${hour}:00–${hour}:59 · ${count} запросов`} style:background={`rgba(96,243,233,${count? .15+.55*count/stats.maxHour:.025})`}><span>{String(hour).padStart(2,'0')}</span><b>{count}</b></div>{/each}</div><div class="heat-legend"><small>Меньше</small>{#each [.025,.2,.4,.7] as opacity}<i style:background={`rgba(96,243,233,${opacity})`}></i>{/each}<small>Больше</small></div>{:else}<p class="chart-empty">После первых запросов здесь появится карта активности.</p>{/if}
        </section>
        <section><div class="chart-heading"><span class="chart-icon">≋</span><div><h3>Самые частые запросы</h3><small>Топ-5 · {stats.unique} разных фраз · количество повторений</small></div></div>
            {#if stats.top.length}<div class="ranking">{#each stats.top as phrase,index}<div class="rank-row"><div class="rank-label"><span class="rank-number">{index+1}</span><span title={phrase.text}>{phrase.text}</span><b>{phrase.count}</b></div><div class="rank-track"><span style:width={`${phrase.count/stats.maxPhrase*100}%`}></span></div></div>{/each}</div>{:else}<p class="chart-empty">Частые запросы появятся по мере накопления истории.</p>{/if}
        </section>
    </div>
    <small>Диаграммы учитывают выбранную категорию и поиск, только сохранённые записи (до 500). Голосовая категория включает разговорные фразы, а не только успешно выполненные команды.</small>
    <p class="count">{filtered.length} запросов</p>
    {#if !filtered.length}<div class="empty">{query||source!=='all'?'По этим условиям ничего не найдено.':'История пока пуста. Новые запросы из чата и голосового режима появятся здесь; старые не восстановлены.'}</div>{:else}
    {#each filtered.slice(0,visible) as item(item.id)}<article><div><span>{item.source==='chat'?'✎ Чат':'🎙 Голос'}</span><time datetime={item.at}>{new Date(item.at).toLocaleString('ru-RU')}</time></div><p>{item.text}</p></article>{/each}
    {#if visible<filtered.length}<button on:click={()=>visible+=50}>Показать ещё</button>{/if}{/if}
</section>
<style>
    .extra-charts{grid-template-columns:repeat(2,minmax(0,1fr))}.chart-heading{display:flex;align-items:center;gap:.7rem;margin-bottom:1.2rem}.chart-icon{display:grid;place-items:center;width:38px;height:38px;border:1px solid #376d70;border-radius:11px;color:#60f3e9;background:#16373b;font-size:1.4rem;flex:none}.hour-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:6px}.hour-cell{display:flex;flex-direction:column;gap:8px;align-items:center;padding:9px 4px;border:1px solid #376268;border-radius:7px;color:#eaffff}.hour-cell span{font-size:.65rem;color:#b4d4d6}.hour-cell b{font-size:.8rem;font-variant-numeric:tabular-nums}.heat-legend{display:flex;justify-content:flex-end;align-items:center;gap:5px;margin-top:.8rem}.heat-legend i{width:12px;height:12px;border:1px solid #376268;border-radius:3px}.ranking{display:grid;gap:1rem}.rank-label{display:flex;align-items:center;gap:.5rem;font-size:.72rem;margin-bottom:.4rem}.rank-label>span:nth-child(2){min-width:0;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.rank-number{display:grid;place-items:center;width:23px;height:23px;border-radius:7px;background:#16373b;color:#60f3e9;flex:none}.rank-label b{font-variant-numeric:tabular-nums}.rank-track{height:8px;background:#203c42;border-radius:4px;overflow:hidden}.rank-track span{display:block;height:100%;background:#60f3e9;border-radius:4px;transition:width .3s ease}.chart-empty{color:#91abb1;font-size:.8rem;line-height:1.8;padding:1.3rem 0}@media(max-width:850px){.extra-charts{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.rank-track span{transition:none}}
    .categories,.terminal{display:flex;align-items:center;flex-wrap:wrap;gap:.5rem;margin:1rem 0}.categories button[aria-pressed="true"]{border-color:#60f3e9;background:#18565c}.terminal span{color:#91abb1;font-size:.75rem;margin-right:auto}.charts{display:grid;grid-template-columns:minmax(0,.8fr) minmax(0,1.4fr);gap:.8rem;margin:1rem 0}.charts section{padding:1rem;border:1px solid #28494f;border-radius:12px;background:#0d1b20;min-width:0}.charts h3{font-size:.9rem;margin:0 0 .4rem}.mix{display:flex;align-items:center;gap:1rem;margin:1.2rem 0}.mix p{font-size:.75rem}.mix b{margin-left:.5rem}.donut{width:115px;height:115px;border-radius:50%;display:grid;place-items:center;flex:none}.donut strong{width:85px;height:85px;display:grid;place-items:center;background:#0d1b20;border-radius:50%;font-size:1.6rem}.bars{display:flex;gap:5px;align-items:end;height:165px;overflow-x:auto;padding-top:1rem}.bars>div{display:flex;flex:1;min-width:22px;flex-direction:column;align-items:center;justify-content:end;height:150px;gap:4px}.bars span{width:100%;background:#60f3e9;min-height:1px;border-radius:3px 3px 0 0}.bars b{font-size:.6rem}.bars small{font-size:.5rem;writing-mode:vertical-rl;height:40px}.terminal button{padding:.5rem .7rem;font-size:.65rem}[role="alert"]{color:#ffb3b3;font-size:.75rem}@media(max-width:850px){.charts{grid-template-columns:1fr}}
    .history{color:#eaffff;font-family:'Manrope Variable',sans-serif}header{display:flex;align-items:center;justify-content:space-between;gap:1rem;flex-wrap:wrap}header p{margin:0;color:#60f3e9;font-size:.65rem;letter-spacing:.15em;font-weight:800}h2{margin:.4rem 0;font-size:1.7rem;letter-spacing:-.035em}small,.count,time{color:#91abb1;font-size:.7rem}.filters{display:flex;gap:.6rem;margin:1.3rem 0}.filters input{flex:1;min-width:0}input,select,button{background:#102b31;color:#eaffff;border:1px solid #31545a;border-radius:9px;padding:.75rem;font:600 .75rem 'Manrope Variable',sans-serif}button{cursor:pointer}button:disabled{opacity:.4}button:hover{border-color:#60f3e9}article{padding:1rem;border:1px solid #28494f;border-radius:12px;background:linear-gradient(120deg,#143237,#0d1b20);margin:.7rem 0}article>div{display:flex;justify-content:space-between;gap:.7rem;flex-wrap:wrap}article span{color:#60f3e9;font-size:.7rem}article p{white-space:pre-wrap;overflow-wrap:anywhere;font-size:.85rem;line-height:1.7;margin:.6rem 0 0}.empty{padding:2rem;border:1px dashed #31545a;border-radius:12px;color:#91abb1;font-size:.8rem;line-height:1.8}input:focus-visible,select:focus-visible,button:focus-visible{outline:2px solid #60f3e9;outline-offset:2px}
</style>
