<script lang="ts">
    import {onMount,onDestroy} from 'svelte'
    import {invoke} from '@tauri-apps/api/core'
    import RichNoteEditor from './RichNoteEditor.svelte'
    import {sanitizeNoteHtml,NOTE_HTML_LIMIT} from '@/lib/richNotes'
    import {createVault,unlockVault,recoverVault,updateVault,type VaultFile,type PasswordCard} from '@/lib/passwordVault'
    let stored:string|null=null,loading=true,busy=false,error='',notice='',recoveryMode=false
    let master='',confirmation='',recoveryInput='',recovery='',recoverySaved=false
    let file:VaultFile|undefined,key:CryptoKey|undefined,cards:PasswordCard[]=[]
    let id='',title='',login='',password='',site='',html='',plainText='',showPassword=false,editorKey=0,dirty=false,query=''
    let lastActivity=Date.now(),disposed=false,timer:ReturnType<typeof setInterval>
    const activity=()=>lastActivity=Date.now()
    function lock(){key=undefined;file=undefined;cards=[];master='';confirmation='';recoveryInput='';recovery='';recoverySaved=false;id='';title='';login='';password='';site='';html='';plainText='';showPassword=false;dirty=false;editorKey++;query=''}
    onMount(()=>{
        invoke<string|null>('password_vault_load').then(value=>{if(!disposed)stored=value}).catch(e=>error=String(e)).finally(()=>loading=false)
        timer=setInterval(()=>{if(key&&!busy&&Date.now()-lastActivity>=300000){lock();notice='Хранилище заблокировано после 5 минут бездействия. Несохранённые изменения очищены.'}},1000)
        window.addEventListener('pointerdown',activity);window.addEventListener('keydown',activity);window.addEventListener('pointermove',activity)
    })
    onDestroy(()=>{disposed=true;clearInterval(timer);window.removeEventListener('pointerdown',activity);window.removeEventListener('keydown',activity);window.removeEventListener('pointermove',activity);lock()})
    async function access(){
        if(busy)return;busy=true;error='';notice=''
        try{
            if(!stored){
                if(master!==confirmation)throw Error('Мастер-пароли не совпадают')
                const created=await createVault(master);if(disposed)return
                file=created.file;key=created.key;recovery=created.recovery;cards=[]
            }else if(recoveryMode){
                if(master!==confirmation)throw Error('Новые мастер-пароли не совпадают')
                const restored=await recoverVault(stored,recoveryInput,master)
                await invoke('password_vault_save',{data:JSON.stringify(restored.file)})
                if(disposed)return
                stored=JSON.stringify(restored.file);file=restored.file;key=restored.key;cards=restored.cards;notice='Мастер-пароль заменён. Прежний ключ восстановления остаётся действующим.'
            }else{const opened=await unlockVault(stored,master);if(disposed)return;file=opened.file;key=opened.key;cards=opened.cards}
            master='';confirmation='';recoveryInput='';recoveryMode=false;activity()
        }catch(e){if(!disposed)error=e instanceof Error?e.message:String(e)}finally{busy=false}
    }
    async function confirmRecovery(){if(!file||!recoverySaved)return;busy=true;error='';try{const data=JSON.stringify(file);await invoke('password_vault_save',{data});if(disposed)return;stored=data;recovery='';recoverySaved=false;notice='Хранилище создано. Ключ восстановления храните отдельно.'}catch(e){error=String(e)}finally{busy=false}}
    function edit(card?:PasswordCard){if(dirty&&!confirm('Перейти без сохранения изменений?'))return;id=card?.id||'';title=card?.title||'';login=card?.login||'';password=card?.password||'';site=card?.site||'';html=sanitizeNoteHtml(card?.html||'');plainText='';showPassword=false;dirty=false;editorKey++;error='';notice=''}
    async function persist(next:PasswordCard[]){if(!file||!key||busy)return false;busy=true;error='';try{const updated=await updateVault(file,key,next);await invoke('password_vault_save',{data:JSON.stringify(updated)});if(disposed)return false;file=updated;stored=JSON.stringify(updated);cards=next;notice='Сохранено в зашифрованном хранилище';return true}catch(e){error=e instanceof Error?e.message:String(e);return false}finally{busy=false;activity()}}
    async function save(){if(!title.trim()){error='Укажите название карточки';return}const safe=sanitizeNoteHtml(html);if(safe.length>NOTE_HTML_LIMIT){error='Карточка превышает 8 МБ';return}const card={id:id||crypto.randomUUID(),title:title.trim(),login,password,site,html:safe,updatedAt:new Date().toISOString()};if(await persist([...cards.filter(item=>item.id!==card.id),card])){id=card.id;dirty=false}}
    async function remove(){if(confirm('Удалить эту карточку из хранилища?')&&await persist(cards.filter(card=>card.id!==id))){dirty=false;edit()}}
    $: visible=cards.filter(card=>card.title.toLocaleLowerCase('ru-RU').includes(query.toLocaleLowerCase('ru-RU'))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))
</script>
<section class="vault" aria-label="Хранилище паролей">
    <header><div><p class="eyebrow">JARVIS / PRIVATE VAULT</p><h2>Пароли и личные записи</h2><small>Локальное шифрование · без отправки в нейросеть</small></div>{#if key}<button disabled={busy} on:click={()=>{lock();notice='Хранилище заблокировано'}}>◇ Заблокировать</button>{/if}</header>
    {#if error}<p role="alert" class="error">{error}</p>{/if}{#if notice}<p role="status" class="notice">{notice}</p>{/if}
    {#if loading}<p>Открываю хранилище…</p>
    {:else if recovery}<div class="gate"><h3>Сохраните ключ восстановления</h3><p>Он даёт доступ ко всем карточкам без мастер-пароля. Запишите на бумаге или сохраните в отдельном защищённом месте. Не храните рядом с файлом хранилища.</p><textarea readonly aria-label="Ключ восстановления" value={recovery}></textarea><small>Показывается только сейчас. Для переноса или восстановления после сбоя также нужна копия зашифрованного файла password-vault-v1.json из папки данных приложения.</small><label class="check"><input type="checkbox" bind:checked={recoverySaved}/> Я сохранил ключ вне JARVIS</label><button class="primary" disabled={!recoverySaved||busy} on:click={confirmRecovery}>Подтвердить и создать хранилище</button><button disabled={busy} on:click={lock}>Отменить</button></div>
    {:else if !key}<form class="gate" on:submit|preventDefault={access}><h3>{!stored?'Создайте мастер-пароль':recoveryMode?'Восстановление доступа':'Разблокируйте хранилище'}</h3><p>{recoveryMode?'Введите сохранённый ключ восстановления и задайте новый мастер-пароль.':'Один мастер-пароль защищает карточки, текст и картинки.'}</p>{#if recoveryMode}<label>Ключ восстановления<input type="password" bind:value={recoveryInput} required autocomplete="off"/></label>{/if}<label>{recoveryMode?'Новый мастер-пароль':'Мастер-пароль'}<input type="password" bind:value={master} required autocomplete="off" disabled={busy}/></label>{#if !stored||recoveryMode}<label>Повторите мастер-пароль<input type="password" bind:value={confirmation} required autocomplete="off" disabled={busy}/></label><small>Минимум 6 символов. Используйте уникальную длинную фразу.</small>{/if}<button class="primary" disabled={busy}>{busy?'Обрабатываю…':!stored?'Создать хранилище':recoveryMode?'Заменить мастер-пароль':'Разблокировать'}</button>{#if stored}<button type="button" disabled={busy} on:click={()=>{recoveryMode=!recoveryMode;master='';confirmation='';error=''}}>{recoveryMode?'Вернуться к паролю':'Забыли мастер-пароль?'}</button>{/if}<small>Блокировка через 5 минут бездействия и при выходе из раздела. Без мастер-пароля и ключа восстановления доступ восстановить нельзя.</small></form>
    {:else}<div class="layout"><aside><button class="primary" disabled={busy} on:click={()=>edit()}>＋ Новая карточка</button><input aria-label="Поиск карточек" placeholder="Поиск по названию" bind:value={query}/>{#if !visible.length}<small>Карточек пока нет.</small>{/if}{#each visible as card}<button class:active={id===card.id} disabled={busy} on:click={()=>edit(card)}><strong>{card.title}</strong><small>{new Date(card.updatedAt).toLocaleDateString('ru-RU')}</small></button>{/each}</aside><form on:submit|preventDefault={save}><fieldset disabled={busy}><label>Название<input bind:value={title} on:input={()=>dirty=true} maxlength="100" required placeholder="Например, почта"/></label><div class="fields"><label>Логин<input bind:value={login} on:input={()=>dirty=true} autocomplete="off"/></label><label>Сайт<input bind:value={site} on:input={()=>dirty=true} placeholder="https://…"/></label></div><label>Пароль<div class="password"><input type={showPassword?'text':'password'} value={password} on:input={event=>{password=event.currentTarget.value;dirty=true}} autocomplete="off"/><button type="button" aria-pressed={showPassword} on:click={()=>showPassword=!showPassword}>{showPassword?'Скрыть':'Показать'}</button></div></label><p class="caption">Личная запись и вложения · картинки через Ctrl+V</p>{#key editorKey}<RichNoteEditor bind:html bind:plainText disabled={busy} on:change={()=>dirty=true}/>{/key}<div class="actions"><button class="primary">Сохранить карточку</button>{#if id}<button type="button" class="danger" on:click={remove}>Удалить</button>{/if}</div><small>{dirty?'Есть несохранённые изменения':'Текст и картинки сохраняются только в зашифрованном файле.'}</small></fieldset></form></div>{/if}
</section>
<style>
    .vault{color:#eaffff;font-family:'Manrope Variable',sans-serif}header{display:flex;justify-content:space-between;align-items:center;gap:1rem;flex-wrap:wrap;margin-bottom:1rem}.eyebrow{margin:0;color:#60f3e9;letter-spacing:.15em;font-size:.65rem;font-weight:800}h2{margin:.4rem 0;font-size:1.7rem;letter-spacing:-.035em}small,.caption{color:#91abb1;font-size:.7rem;line-height:1.7}.gate{display:grid;gap:.85rem;padding:1.3rem;border:1px solid #31545a;border-radius:14px;background:#10282d;max-width:600px}.gate h3{margin:0;font-size:1.1rem}.gate p{font-size:.8rem;line-height:1.8;margin:0;color:#b7cdd0}label{display:grid;gap:.4rem;font-size:.75rem;color:#c7e3e5}input,textarea,button{min-width:0;background:#09171b;color:#eaffff;border:1px solid #31545a;border-radius:8px;padding:.75rem;font:600 .75rem 'Manrope Variable',sans-serif}button{cursor:pointer}button:disabled{opacity:.5}.primary{background:#168e90;border-color:#60f3e9;color:#eaffff}.gate textarea{height:75px;resize:none;overflow-wrap:anywhere;user-select:all}.check{display:flex;align-items:center;gap:.6rem}.check input{accent-color:#60f3e9}.layout{display:grid;grid-template-columns:180px minmax(0,1fr);gap:1rem}aside{display:flex;flex-direction:column;gap:.5rem;max-height:600px;overflow:auto}aside button{text-align:left;overflow-wrap:anywhere}aside strong,aside small{display:block}aside .active{border-color:#60f3e9;background:#18565c}fieldset{display:grid;gap:.8rem;min-width:0;border:1px solid #31545a;padding:1rem;border-radius:12px;background:#0d1b20}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.6rem}.password,.actions{display:flex;gap:.5rem}.password input{flex:1}.danger{color:#ffb3b3}.caption{margin:.4rem 0}.error,.notice{padding:.7rem;border-radius:8px;font-size:.75rem;line-height:1.7}.error{background:#351c21;color:#ffc4c4;border:1px solid #805157}.notice{background:#123d3b;color:#b6f7ea;border:1px solid #3c8f87}input:focus-visible,button:focus-visible,textarea:focus-visible{outline:2px solid #60f3e9;outline-offset:2px}@media(max-width:700px){.layout,.fields{grid-template-columns:1fr}aside{max-height:220px}}
</style>
