[[commands]]
id = "vscode_open"
type = "ahk"
exe_path = "ahk/Open VS Code.exe"
sounds.ru = ["ok1", "ok2", "ok3"]
phrases.ru = ["открой вс код", "открой vscode", "запусти вс код", "запусти vscode", "открой visual studio code"]

[[commands]]
id = "vscode_close"
type = "ahk"
exe_path = "ahk/Close VS Code.exe"
sounds.ru = ["ok1", "ok2", "ok3"]
phrases.ru = ["закрой вс код", "закрой vscode", "выключи вс код", "закрой visual studio code"]
