[[commands]]
id = "test_greet_name"
type = "lua"
description = "Поздороваться с человеком по имени"
script = "greet.lua"
timeout = 10000

[commands.phrases]
en = ["say hello to {name}", "greet {name}"]
ru = ["поздоровайся с {name}", "привет {name}"]
