// node --conditions=browser tests/commands-order.cjs <test dependency directory>
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{createRequire,Module}=require('node:module')
const deps=createRequire(path.resolve(process.argv[2],'package.json')),{JSDOM}=deps('jsdom')
const dom=new JSDOM('<!doctype html><body></body>',{url:'http://localhost'})
dom.window.matchMedia=()=>({matches:false})
dom.window.HTMLElement.prototype.setPointerCapture=()=>{}
dom.window.scrollBy=()=>{}
for(const name of ['window','document','navigator','HTMLElement','Node','Event','MouseEvent','getComputedStyle','localStorage'])Object.defineProperty(globalThis,name,{value:dom.window[name],configurable:true})
const {screen,waitFor,fireEvent,within}=deps('@testing-library/dom'),userEvent=deps('@testing-library/user-event').default
const ts=require('typescript'),{compile,preprocess}=require('svelte/compiler')
async function main(){
 const svelte=await import('svelte'),store=await import('svelte/store')
 const filename=path.resolve('src/routes/commands/index.svelte')
 const processed=await preprocess(fs.readFileSync(filename,'utf8'),{script:({content})=>({code:ts.transpileModule(content,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,verbatimModuleSyntax:true}}).outputText})},{filename})
 const empty=new Module(filename,module);empty.paths=module.paths;empty._compile(ts.transpileModule(compile('<span></span>',{generate:'dom'}).js.code,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,filename)
 const fixtures=['discord_open','telegram_open','open_browser','weather'].map(id=>({id,type:'voice',description:id,phrases:{ru:[id]}}))
 const mod=new Module(filename,module);mod.paths=module.paths
 mod.require=name=>name==='svelte'?svelte:name==='@/stores'?{currentLanguage:store.writable('ru')}:name==='@tauri-apps/api/core'?{invoke:async()=>fixtures}:name.endsWith('.css')?{}:name.endsWith('.svelte')?empty.exports:require(name)
 mod._compile(ts.transpileModule(compile(processed.code,{filename,generate:'dom',css:'external'}).js.code,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,filename)
 const Component=mod.exports.default,user=userEvent.setup({document})
 let component=new Component({target:document.body})
 await screen.findByText('discord_open',{selector:'.description'})
 await user.click(screen.getByRole('button',{name:'Категории'}))
 const order=()=>screen.getAllByRole('region').map(el=>el.getAttribute('aria-label')).filter(Boolean)
 assert.deepEqual(order(),['Приложения','Интернет и сайты','Погода и город'])
 await user.click(screen.getByRole('button',{name:'Переместить категорию Приложения вниз'}))
 assert.deepEqual(order(),['Интернет и сайты','Приложения','Погода и город'])
 assert.deepEqual(within(screen.getByRole('region',{name:'Приложения'})).getAllByRole('article').map(el=>within(el).getByRole('heading').textContent),['discord open','telegram open'])
 component.$destroy();document.body.innerHTML=''
 component=new Component({target:document.body});await screen.findByRole('region',{name:'Приложения'})
 assert.deepEqual(order(),['Интернет и сайты','Приложения','Погода и город'])
 document.elementFromPoint=()=>screen.getByRole('region',{name:'Интернет и сайты'})
 fireEvent(screen.getByRole('button',{name:'Перетащить категорию Погода и город'}),new MouseEvent('pointerdown',{bubbles:true,button:0,clientY:150}))
 fireEvent(window,new MouseEvent('pointermove',{bubbles:true,clientY:250}))
 await svelte.tick()
 fireEvent(window,new MouseEvent('pointerup',{bubbles:true,clientY:250}))
 await waitFor(()=>assert.deepEqual(order(),['Погода и город','Интернет и сайты','Приложения']))
 assert.ok(screen.getByRole('button',{name:'Переместить категорию Погода и город вверх'}).disabled)
 await user.click(screen.getByRole('button',{name:'Список'}))
 assert.deepEqual(screen.getAllByRole('article').map(el=>within(el).getByRole('heading').textContent),['discord open','telegram open','open browser','weather'])
 assert.ok(screen.getAllByRole('article').every(el=>!el.draggable))
 fixtures.push({id:'outlook_compose',type:'center',description:'Продиктовать получателя, тему и текст письма',phrases:{ru:['напиши письмо']}})
 window.dispatchEvent(new Event('focus'))
 await screen.findByRole('heading',{name:'Написать письмо'})
 await user.click(screen.getByRole('button',{name:'Категории'}))
 assert.ok(within(screen.getByRole('region',{name:'Outlook и почта'})).getByRole('heading',{name:'Написать письмо'}))
 await user.click(screen.getByText('Пример: написать тестовое письмо'))
 assert.ok(screen.getByText(/Джарвис, адрес указал/))
 assert.ok(screen.getByText(/Да, отправить/))
 assert.ok(screen.getByText(/работает только в нашей локальной лаборатории/))
 await user.type(screen.getByLabelText('ПОИСК'),'напиши письмо')
 assert.equal(screen.getAllByRole('article').length,1,'mail example stays discoverable through command search')
 component.$destroy();console.log('Category arrows, drag/drop, persistence and unchanged command order passed')
}
main().then(()=>process.exit(0)).catch(error=>{console.error(error);process.exit(1)})
