// Run: node --conditions=browser tests/training.cjs <test dependency directory>
const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict')
const { createRequire, Module } = require('node:module')
const deps = createRequire(path.resolve(process.argv[2], 'package.json'))
const { JSDOM } = deps('jsdom')
const dom = new JSDOM('<!doctype html><body></body>', { url: 'http://localhost' })
for (const name of ['window', 'document', 'navigator', 'HTMLElement', 'Node', 'Event', 'MouseEvent', 'getComputedStyle', 'localStorage']) Object.defineProperty(globalThis, name, { value: dom.window[name], configurable: true })
global.confirm = () => true
const { screen, waitFor } = deps('@testing-library/dom')
const userEvent = deps('@testing-library/user-event').default
const ts = require('typescript'), { compile, preprocess } = require('svelte/compiler')
function evaluate(code, filename, overrides = {}) {
    const mod = new Module(filename, module); mod.filename = filename; mod.paths = module.paths
    mod.require = name => overrides[name] || require(name)
    mod._compile(ts.transpileModule(code, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText, filename)
    return mod.exports
}
async function main() {
    const svelte = await import('svelte'), stores = await import('svelte/store')
    const engine = evaluate(fs.readFileSync('src/lib/training.ts', 'utf8'), path.resolve('src/lib/training.ts'))
    const center = { dayKey: date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}` }
    const stats = evaluate(fs.readFileSync('src/lib/trainingStats.ts','utf8'),path.resolve('src/lib/trainingStats.ts'),{'./center':center,'./training':engine})
    const planner = evaluate(fs.readFileSync('src/lib/trainingPlanner.ts','utf8'),path.resolve('src/lib/trainingPlanner.ts'),{'./center':center,'./training':engine})
    const testNow=new Date('2026-10-01T12:00:00').getTime()
    const ready={fatigue:1,pain:false,mood:4}
    const plannerData={...engine.defaultTraining(),profile:{heightCm:180,measurements:[],experience:'Опытный',preferredLevel:6}}
    assert.equal(planner.dailyProposal(plannerData,{...ready,pain:true},true,testNow).rest,true)
    assert.equal(planner.dailyProposal(plannerData,{...ready,fatigue:5},true,testNow).rest,true)
    const recent=engine.newTraining(plannerData.plans[0],plannerData.exercises,testNow-24*3600000,{plannedLevel:6})
    recent.status='completed';recent.finishedAt=new Date(testNow-23*3600000).toISOString()
    recent.sets=[{id:'p',exerciseId:'bench',weight:45,reps:8,rpe:9,warmup:false,at:recent.startedAt}]
    plannerData.sessions=[recent]
    for(let i=0;i<100;i++){
        const proposed=planner.dailyProposal(plannerData,ready,true,testNow,()=>i/100)
        assert.ok(proposed.level<=2)
        assert.ok(proposed.plan.items.every(item=>plannerData.exercises.find(e=>e.id===item.exerciseId).muscle!=='Грудь'))
    }
    const charge=planner.chargeProposal([{id:'walk',name:'Шаги',hint:'1 минута'}],plannerData,ready,true,testNow,()=>0)
    assert.ok(charge.level<=1)
    assert.equal(planner.chargeProposal([],plannerData,{...ready,pain:true},true,testNow).blocked,true)
    const timer = evaluate(fs.readFileSync('src/lib/timer.ts', 'utf8'), path.resolve('src/lib/timer.ts'), { 'svelte/store': stores, '@/lib/ipc': { activeNotification: stores.writable(null) } })
    let saved = engine.defaultTraining(), habit
    assert.equal(saved.sessions.length, 0)
    assert.equal(engine.validateSet(NaN, 8, 8), false)
    assert.equal(engine.validateSet(45, 0, 8), false)
    assert.equal(engine.validateSet(0, 8, null), true)
    const t = engine.newTraining(saved.plans[0], saved.exercises, 1000)
    const paused = engine.changeTrainingStatus(t, 'paused', 6000)
    assert.equal(engine.trainingDuration(paused, 50000), 5000)
    const resumed = engine.changeTrainingStatus(paused, 'active', 10000)
    assert.equal(engine.trainingDuration(resumed, 12000), 7000)
    const fixture = { id:'set', exerciseId:'bench', weight:80, reps:8, rpe:8, warmup:false, at:new Date().toISOString() }
    assert.equal(engine.trainingVolume({ ...t, sets:[fixture, {...fixture, warmup:true}] }), 640)
    assert.equal(engine.estimatedMax({...fixture,reps:11}), null)
    assert.match(engine.progression(t.items[0],[fixture,fixture,fixture]), /небольшой шаг/)
    assert.equal(stats.trainingTotals([{...t,status:'completed',mood:null},{...t,status:'completed',mood:4}]).mood,4)
    assert.equal(stats.relativeStrength({...t,sets:[fixture],bodyWeight:80},'bench'),engine.estimatedMax(fixture)/80)
    assert.equal(stats.relativeStrength({...t,sets:[fixture]},'bench'),null)
    const chart = stats.chartPoints([{date:'2026-01-01',value:80},{date:'2026-01-02',value:79},{date:'2026-01-11',value:78}])
    assert.ok(chart.points[1].x-chart.points[0].x<chart.points[2].x-chart.points[1].x)
    const statsFilename = path.resolve('src/components/TrainingStats.svelte')
    const bodyFilename = path.resolve('src/components/TrainingBody.svelte')
    const bodyProcessed = await preprocess(fs.readFileSync(bodyFilename,'utf8'),require('svelte-preprocess')(),{filename:bodyFilename})
    const bodyCompiled = compile(bodyProcessed.code,{filename:bodyFilename,generate:'dom',css:'external'})
    const BodyComponent = evaluate(bodyCompiled.js.code,bodyFilename,{svelte}).default
    const statsProcessed = await preprocess(fs.readFileSync(statsFilename,'utf8'),require('svelte-preprocess')(),{filename:statsFilename})
    const statsCompiled = compile(statsProcessed.code,{filename:statsFilename,generate:'dom',css:'external'})
    const StatsComponent = evaluate(statsCompiled.js.code,statsFilename,{svelte,'./TrainingBody.svelte':{default:BodyComponent},'@/lib/center':center,'@/lib/training':engine,'@/lib/trainingStats':stats}).default
    const filename = path.resolve('src/components/CenterTraining.svelte')
    const prefFilename = path.resolve('src/components/TrainingPreferences.svelte')
    const prefProcessed = await preprocess(fs.readFileSync(prefFilename,'utf8'),require('svelte-preprocess')(),{filename:prefFilename})
    const prefCompiled = compile(prefProcessed.code,{filename:prefFilename,generate:'dom',css:'external'})
    const PrefComponent = evaluate(prefCompiled.js.code,prefFilename,{svelte,'@/lib/center':center,'@/lib/training':engine}).default
    const processed = await preprocess(fs.readFileSync(filename, 'utf8'), require('svelte-preprocess')(), { filename })
    const compiled = compile(processed.code, { filename, generate:'dom', css:'external' })
    const Component = evaluate(compiled.js.code, filename, { svelte, '@/lib/trainingPlanner':planner, './TrainingPreferences.svelte':{default:PrefComponent}, './TrainingBody.svelte':{default:BodyComponent}, './TrainingStats.svelte':{default:StatsComponent}, '@/lib/trainingStats':stats, '@/lib/training':engine, '@/lib/timer':timer, '@/lib/center':center }).default
    let component
    const props = () => ({ data:JSON.parse(JSON.stringify(saved)), onSave:async (data, mark) => { saved=JSON.parse(JSON.stringify(data)); habit=mark; component.$set({data:saved}); return true } })
    component = new Component({ target:document.body, props:props() })
    const user = userEvent.setup({ document })
    for (const name of ['Сегодня','Зарядка','Программы','Упражнения','История','Рекорды','Статистика']) {
        await user.click(screen.getByRole('button',{name,exact:true}))
        assert.ok(screen.getByRole('img',{name:/Условная фигура человека/}))
    }
    await user.click(screen.getByRole('button',{name:'Сзади',exact:true}))
    assert.equal(screen.queryByRole('button',{name:/Выбрать группу Грудь/}),null)
    await user.click(screen.getByRole('button',{name:'Общее',exact:true}))
    await user.click(screen.getByRole('button',{name:'Группа Грудь',exact:true}))
    assert.equal(screen.getByRole('button',{name:'Группа Грудь',exact:true}).getAttribute('aria-pressed'),'true')
    assert.ok(screen.getByText(/Основная группа для жимов/))
    await user.click(screen.getByRole('button',{name:'Сбросить выбор',exact:true}))
    await user.click(screen.getByRole('button',{name:'Зарядка',exact:true}))
    await user.click(screen.getByRole('checkbox',{name:/Шаги на месте/}))
    await waitFor(()=>assert.equal(saved.morningExercise[center.dayKey(new Date())].includes('walk'),true))
    assert.equal(saved.sessions.length,0)
    await user.click(screen.getByRole('button',{name:'Сегодня',exact:true}))
    await user.click(screen.getByRole('button',{name:'Зарядка',exact:true}))
    assert.equal(screen.getByRole('checkbox',{name:/Шаги на месте/}).checked,true)
    await user.click(screen.getByRole('button',{name:'Статистика',exact:true}))
    assert.ok(screen.getByRole('img',{name:/Условная фигура человека/}))
    assert.equal(screen.queryByRole('spinbutton',{name:'Рост, см'}),null)
    await user.click(screen.getByRole('button',{name:/Изменить рост, вес и другие данные/}))
    await user.type(screen.getByRole('spinbutton',{name:'Рост, см'}),'180')
    await user.type(screen.getByRole('spinbutton',{name:'Новое измерение веса, кг'}),'80')
    await user.click(screen.getByRole('button',{name:'Сохранить настройки'}))
    await waitFor(()=>assert.equal(saved.profile.heightCm,180))
    assert.equal(saved.profile.measurements[0].weight,80)
    await user.click(screen.getByRole('button',{name:'Мои параметры',exact:true}))
    await user.type(screen.getByRole('spinbutton',{name:'Процент жира, %'}),'20')
    await user.selectOptions(screen.getByRole('combobox',{name:'Предпочитаемый уровень нагрузки'}),'3')
    await user.click(screen.getByRole('button',{name:'Сохранить настройки',exact:true}))
    await waitFor(()=>assert.equal(saved.profile.bodyFatPercent,20))
    assert.equal(saved.profile.heightCm,180)
    assert.equal(saved.profile.measurements[0].weight,80)
    await user.click(screen.getByRole('button',{name:'Зарядка',exact:true}))
    await user.click(screen.getByRole('button',{name:'Взять предпочитаемый уровень из профиля'}))
    await user.click(screen.getByRole('button',{name:'Сохранить настройки',exact:true}))
    await waitFor(()=>assert.equal(saved.chargeSettings.level,3))
    assert.match(saved.chargeSettings.steps[0].hint,/60 секунд/)
    await user.click(screen.getByRole('button',{name:'Статистика',exact:true}))
    assert.equal(screen.queryByRole('button',{name:'Сохранить профиль'}),null)
    assert.equal(saved.profile.bodyFatPercent,20)
    await user.click(screen.getByRole('button',{name:'Сегодня',exact:true}))
    await user.selectOptions(screen.getByRole('combobox',{name:'Настроение перед тренировкой'}),'4')
    await user.click(screen.getByRole('button',{name:'Подобрать на сегодня',exact:true}))
    assert.ok(screen.getByRole('button',{name:'Вернуться к ручному выбору'}))
    await user.click(screen.getByRole('button',{name:'Вернуться к ручному выбору'}))
    await user.click(screen.getByRole('button',{ name:'Начать тренировку' }))
    await screen.findByRole('button',{ name:/Завершить подход/ })
    assert.equal(saved.sessions[0].heightCm,180)
    assert.equal(saved.sessions[0].bodyWeight,80)
    assert.equal(saved.sessions[0].mood,4)
    const weight = screen.getByRole('spinbutton',{ name:/Вес, кг/ })
    await user.clear(weight); await user.type(weight,'45')
    await user.click(screen.getByRole('button',{ name:/Завершить подход/ }))
    await waitFor(()=>assert.equal(saved.sessions[0].sets.length,1))
    assert.equal(saved.sessions[0].sets[0].weight,45)
    assert.equal(stores.get(timer.timerState).phase,'running')
    assert.equal(stores.get(timer.timerState).owner,saved.sessions[0].id)
    await user.click(screen.getByRole('checkbox',{ name:/Разминочный подход/ }))
    await user.click(screen.getByRole('button',{ name:/Завершить подход/ }))
    assert.equal(engine.workingSets(saved.sessions[0]).length,1)
    await user.click(screen.getAllByRole('button',{ name:'Пауза',exact:true })[0])
    assert.equal(saved.sessions[0].status,'paused')
    component.$destroy()
    component = new Component({ target:document.body, props:props() })
    await user.click(screen.getByRole('button',{name:'Продолжить',exact:true}))
    assert.equal(saved.sessions[0].status,'active')
    await user.click(screen.getByRole('button',{name:'Завершить',exact:true}))
    await waitFor(()=>assert.equal(saved.sessions[0].status,'completed'))
    assert.equal(habit,'Сходил в зал')
    await user.click(screen.getByRole('button',{name:'Рекорды',exact:true}))
    assert.ok(screen.getByText(/Лучший вес: 45 кг/))
    await user.click(screen.getByRole('button',{name:'Упражнения',exact:true}))
    await user.type(screen.getByRole('textbox',{name:'Название',exact:true}),'Мой тренажёр')
    await user.click(screen.getByRole('button',{name:'Добавить в библиотеку'}))
    assert.ok(saved.exercises.some(item=>item.name==='Мой тренажёр'))
    await user.click(screen.getByRole('button',{name:'Программы',exact:true}))
    await user.click(screen.getByRole('button',{name:'+ Создать',exact:true}))
    await user.click(screen.getByRole('button',{name:'Добавить',exact:true}))
    await user.click(screen.getByRole('button',{name:'Сохранить программу'}))
    assert.equal(saved.plans.length,5)
    await user.click(screen.getByRole('button',{name:'Уровень из профиля',exact:true}))
    await user.click(screen.getByRole('button',{name:'Создать вариант',exact:true}))
    await user.click(screen.getByRole('button',{name:'Сохранить программу'}))
    assert.equal(saved.plans.length,6)
    assert.equal(saved.plans.at(-1).items[0].sets,3)
    component.$destroy()
    console.log('PASS: body statistics, profile/weight persistence, mood and body context snapshots, honest missing values and chart spacing; training lifecycle and rest timer')
}
main().catch(error=>{console.error(error);process.exit(1)})
